-- Run in a new Supabase project, separate from the original tracker.
create extension if not exists pgcrypto;
create table families (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), name text not null default 'My Family', primary_color text not null default '#075b78', accent_color text not null default '#eb8b4b', logo_url text, created_at timestamptz not null default now());
create table family_members (family_id uuid not null references families(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, primary key(family_id,user_id));
create table swimmers (id uuid primary key default gen_random_uuid(), family_id uuid not null references families(id) on delete cascade, name text not null, team text not null default '', accent_color text, created_at timestamptz not null default now());
create table access_grants (swimmer_id uuid not null references swimmers(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, permission text not null check(permission in ('view','edit')), primary key(swimmer_id,user_id));
create table family_invites (id uuid primary key default gen_random_uuid(), family_id uuid not null references families(id) on delete cascade, email text not null, created_at timestamptz not null default now(), unique(family_id,email));
create table swims (id uuid primary key default gen_random_uuid(), swimmer_id uuid not null references swimmers(id) on delete cascade, event text not null, course text not null default 'SCY', place text not null default '', date date not null, seconds numeric not null check(seconds > 0), official boolean not null default true, splits text not null default '', notes text not null default '', updated_at timestamptz not null default now());
create table goals (id uuid primary key default gen_random_uuid(), swimmer_id uuid not null references swimmers(id) on delete cascade, event text not null, course text not null default 'SCY', personal numeric check(personal > 0), b numeric check(b > 0), bb numeric check(bb > 0), a numeric check(a > 0), aa numeric check(aa > 0), unique(swimmer_id,event,course));
create table meets (id uuid primary key default gen_random_uuid(), swimmer_id uuid not null references swimmers(id) on delete cascade, name text not null, date date not null, place text not null default '', notes text not null default '');
create table meet_events (id uuid primary key default gen_random_uuid(), meet_id uuid not null references meets(id) on delete cascade, event text not null, course text not null default 'SCY', target numeric check(target > 0), swim_id uuid references swims(id) on delete set null);
create table family_lists (family_id uuid not null references families(id) on delete cascade, kind text not null check(kind in ('event','course','place')), value text not null, primary key(family_id,kind,value));

create function is_family_owner(fid uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from families where id=fid and owner_id=(select auth.uid())) $$;
create function is_family_member(fid uuid) returns boolean language sql stable security definer set search_path = public as $$ select is_family_owner(fid) or exists(select 1 from family_members where family_id=fid and user_id=(select auth.uid())) $$;
create function can_view_swimmer(sid uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from swimmers s where s.id=sid and (is_family_owner(s.family_id) or exists(select 1 from access_grants g where g.swimmer_id=sid and g.user_id=(select auth.uid())))) $$;
create function can_edit_swimmer(sid uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from swimmers s where s.id=sid and (is_family_owner(s.family_id) or exists(select 1 from access_grants g where g.swimmer_id=sid and g.user_id=(select auth.uid()) and g.permission='edit'))) $$;
create function owns_meet(mid uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from meets where id=mid and can_edit_swimmer(swimmer_id)) $$;
create function sees_meet(mid uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from meets where id=mid and can_view_swimmer(swimmer_id)) $$;
create function invite_email_matches(em text) returns boolean language sql stable security definer set search_path = public as $$ select lower(trim(em))=lower(coalesce((select email from auth.users where id=(select auth.uid())),'')) $$;

alter table families enable row level security;
alter table family_members enable row level security;
alter table swimmers enable row level security;
alter table access_grants enable row level security;
alter table family_invites enable row level security;
alter table swims enable row level security;
alter table goals enable row level security;
alter table meets enable row level security;
alter table meet_events enable row level security;
alter table family_lists enable row level security;
create policy families_select on families for select to authenticated using (owner_id=(select auth.uid()) or is_family_member(id));
create policy families_insert on families for insert to authenticated with check(owner_id=(select auth.uid()));
create policy families_update on families for update to authenticated using(is_family_owner(id)) with check(is_family_owner(id));
create policy members_select on family_members for select to authenticated using(is_family_member(family_id));
create policy members_insert on family_members for insert to authenticated with check(is_family_owner(family_id) or (user_id=(select auth.uid()) and exists(select 1 from family_invites where family_id=family_members.family_id and invite_email_matches(email))));
create policy members_delete on family_members for delete to authenticated using(is_family_owner(family_id));
create policy swimmers_select on swimmers for select to authenticated using (is_family_owner(family_id) or can_view_swimmer(id));
create policy swimmers_insert on swimmers for insert to authenticated with check(is_family_owner(family_id));
create policy swimmers_update on swimmers for update to authenticated using(is_family_owner(family_id)) with check(is_family_owner(family_id));
create policy swimmers_delete on swimmers for delete to authenticated using(is_family_owner(family_id));
create policy grants_select on access_grants for select to authenticated using(can_view_swimmer(swimmer_id) or user_id=(select auth.uid()));
create policy grants_insert on access_grants for insert to authenticated with check(exists(select 1 from swimmers s where s.id=swimmer_id and is_family_owner(s.family_id) and exists(select 1 from family_members m where m.family_id=s.family_id and m.user_id=access_grants.user_id)));
create policy grants_update on access_grants for update to authenticated using(exists(select 1 from swimmers s where s.id=swimmer_id and is_family_owner(s.family_id))) with check(exists(select 1 from swimmers s where s.id=swimmer_id and is_family_owner(s.family_id)));
create policy grants_delete on access_grants for delete to authenticated using(exists(select 1 from swimmers s where s.id=swimmer_id and is_family_owner(s.family_id)));
create policy invites_select on family_invites for select to authenticated using(is_family_owner(family_id) or invite_email_matches(email));
create policy invites_insert on family_invites for insert to authenticated with check(is_family_owner(family_id));
create policy invites_delete on family_invites for delete to authenticated using(is_family_owner(family_id) or invite_email_matches(email));
create policy swims_select on swims for select to authenticated using(can_view_swimmer(swimmer_id));
create policy swims_insert on swims for insert to authenticated with check(can_edit_swimmer(swimmer_id));
create policy swims_update on swims for update to authenticated using(can_edit_swimmer(swimmer_id)) with check(can_edit_swimmer(swimmer_id));
create policy swims_delete on swims for delete to authenticated using(can_edit_swimmer(swimmer_id));
create policy goals_select on goals for select to authenticated using(can_view_swimmer(swimmer_id));
create policy goals_insert on goals for insert to authenticated with check(can_edit_swimmer(swimmer_id));
create policy goals_update on goals for update to authenticated using(can_edit_swimmer(swimmer_id)) with check(can_edit_swimmer(swimmer_id));
create policy goals_delete on goals for delete to authenticated using(can_edit_swimmer(swimmer_id));
create policy meets_select on meets for select to authenticated using(can_view_swimmer(swimmer_id));
create policy meets_insert on meets for insert to authenticated with check(can_edit_swimmer(swimmer_id));
create policy meets_update on meets for update to authenticated using(can_edit_swimmer(swimmer_id)) with check(can_edit_swimmer(swimmer_id));
create policy meets_delete on meets for delete to authenticated using(can_edit_swimmer(swimmer_id));
create policy meet_events_select on meet_events for select to authenticated using(sees_meet(meet_id));
create policy meet_events_insert on meet_events for insert to authenticated with check(owns_meet(meet_id));
create policy meet_events_update on meet_events for update to authenticated using(owns_meet(meet_id)) with check(owns_meet(meet_id));
create policy meet_events_delete on meet_events for delete to authenticated using(owns_meet(meet_id));
create policy lists_select on family_lists for select to authenticated using(is_family_member(family_id));
create policy lists_insert on family_lists for insert to authenticated with check(is_family_owner(family_id));
create policy lists_delete on family_lists for delete to authenticated using(is_family_owner(family_id));
